env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - standard
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  project:
    - ./tsconfig.json
    - ./test/tsconfig.json
plugins:
  - "@typescript-eslint"
  - simple-import-sort
rules:
  no-dupe-class-members: off
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
        - asyncIteration
  "@typescript-eslint/explicit-function-return-type":
    - warn
    - allowExpressions: true
  simple-import-sort/sort: error
  prettier/prettier: error
overrides:
  - files:
      - "*.d.ts"
    rules:
      no-useless-constructor: off
