# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# no PR builds
pr: none

jobs:
  - template: azure-pipelines-templates/jobs/lint.yml

  - template: azure-pipelines-templates/jobs/unit-test.yml
    parameters:
      name: Linux
      vmImage: ubuntu-latest

  - template: azure-pipelines-templates/jobs/external-api.yml
    variables:
      NETLIFY_API_SITE_ID: peaceful-shockley-c9f989.netlify.com
