# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# no PR builds
pr: none

jobs:
  - template: azure-pipelines-templates/jobs/single-test.yml
    parameters:
      jobName: Lint
      stepLabel: Run linter
      script: npx run-s test:peer-deps lint test:check-type-defs-pkgs

  - template: azure-pipelines-templates/jobs/multi-test.yml
    parameters:
      jobName: UnitTest_Linux
      vmImage: ubuntu-latest
      stepLabel: Run unit test
      script: npm run test:ava

  - template: azure-pipelines-templates/jobs/single-test.yml
    parameters:
      jobName: External_API
      stepLabel: Run external API test
      script: npx ava ./test/netlify-api.ts
      variables:
        NETLIFY_API_SITE_ID: peaceful-shockley-c9f989.netlify.com
      env:
        NETLIFY_API_ACCESS_TOKEN: $(NETLIFY_API_ACCESS_TOKEN)
