[build]
command = 'echo "1. pwd: $(pwd)" && npm ci && echo "2. pwd: $(pwd)" && npm run build && echo "3. pwd: $(pwd)" && cd example/ && echo "4. pwd: $(pwd)" && npm install && echo "5. pwd: $(pwd)" && node_modules/.bin/metalsmith && echo "6. pwd: $(pwd)"'
publish = 'example/build'
