jobs:
  - job: External_API

    pool:
      vmImage: ubuntu-latest

    steps:
      - template: ../steps/init-node.yml

      - script: npx ava ./test/netlify-api.ts
        displayName: Run external API test
        timeoutInMinutes: 5

    cancelTimeoutInMinutes: 1
