jobs:
  - job: External-API

    pool:
      vmImage: ubuntu-latest

    variables:
      NETLIFY_API_SITE_ID: peaceful-shockley-c9f989.netlify.com

    steps:
      - template: ../steps/init-node.yml

      - script: npx ava ./test/netlify-api.ts
        displayName: Run external API test
        timeoutInMinutes: 5

    cancelTimeoutInMinutes: 1
